// flow-typed signature: 3a59cb287ce3179b4823b48f871c35de
// flow-typed version: <<STUB>>/react-swipe-component_v^1.3.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipe-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipe-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipe-component/lib/Swipe' {
  declare module.exports: any;
}

declare module 'react-swipe-component/lib/Swipe.min' {
  declare module.exports: any;
}

declare module 'react-swipe-component/src/Swipe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipe-component/lib/Swipe.js' {
  declare module.exports: $Exports<'react-swipe-component/lib/Swipe'>;
}
declare module 'react-swipe-component/lib/Swipe.min.js' {
  declare module.exports: $Exports<'react-swipe-component/lib/Swipe.min'>;
}
declare module 'react-swipe-component/src/Swipe.js' {
  declare module.exports: $Exports<'react-swipe-component/src/Swipe'>;
}
