// flow-typed signature: a62fd92f8f3b8366b18dc654b422ac3b
// flow-typed version: <<STUB>>/superagent-rxjs_v^2.2.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-rxjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-rxjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-rxjs/es6/index' {
  declare module.exports: any;
}

declare module 'superagent-rxjs/lib/index' {
  declare module.exports: any;
}

declare module 'superagent-rxjs/umd/superagent-rxjs' {
  declare module.exports: any;
}

declare module 'superagent-rxjs/umd/superagent-rxjs.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-rxjs/es6/index.js' {
  declare module.exports: $Exports<'superagent-rxjs/es6/index'>;
}
declare module 'superagent-rxjs/lib/index.js' {
  declare module.exports: $Exports<'superagent-rxjs/lib/index'>;
}
declare module 'superagent-rxjs/umd/superagent-rxjs.js' {
  declare module.exports: $Exports<'superagent-rxjs/umd/superagent-rxjs'>;
}
declare module 'superagent-rxjs/umd/superagent-rxjs.min.js' {
  declare module.exports: $Exports<'superagent-rxjs/umd/superagent-rxjs.min'>;
}
